apiVersion: v1
kind: Service
metadata:
  name: facebook-backend-service
  labels:
    app: facebook-backend
spec:
  selector:
      app: "facebook-backend"
  ports:
  - protocol: TCP
    port: 80    
    targetPort: 80
  type: ClusterIP


