apiVersion: v1
kind: Service
metadata:
  name: facebook-backend-service
  labels:
    app: facebook-backend
spec:
  selector:
    app: facebook-backend  # Matches Pods created by facebook-backend-deployment
  ports:
    - protocol: TCP
      port: 80              # The port that the Service will expose
      targetPort: 80
      nodePort: 30007       # Exposes the Service on a static port across each Node in the cluster.
  type: ClusterIP  # Exposes the Service only within the cluster (default)
