apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook-backend-deployment
  labels:
    app: facebook-backend
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: facebook-backend
  template:
    metadata:
      labels:
        app: facebook-backend
    spec:
      containers:
      - name: backend
        image: nginx:latest
        ports:
        - containerPort: 80